name: keepnote
description: "Note Keeping App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  go_router: ^14.8.1
  shared_preferences: ^2.5.2
  lottie: ^3.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher.png"
  adaptive_icons_background: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins-regular.ttf
          style: normal